#!/bin/bash

cd "$(dirname "$0")" || exit 1

echo "removing non-essential files generated by pdflatex.."

rm -f ./*.aux
rm -f ./*.fdb_latexmk
rm -f ./*.fls
rm -f ./*.log
rm -f ./*.out
rm -f ./*.swp
rm -f ./*.synctex.gz
