job_analysis_task:
  description: >
    Analyze the job posting URL provided ({job_posting_url}) to extract and structure
    the following information:
    - Job title and company name
    - Industry sector
    - Complete job description
    - Experience level required (entry, mid, senior, etc.)
    - General requirements (education, certifications, years of experience)
    - Required skills (must-have technical and soft skills)
    - Preferred skills (nice-to-have skills that give candidates an advantage)
    - Key responsibilities and day-to-day activities
    Use the scraping and search tools to gather comprehensive information.
  expected_output: >
    A structured JobPosting object containing title, company, industry,
    description, experience_level, requirements, required_skills,
    preferred_skills, and responsibilities extracted from the job posting.
  output_file: "{output_directory}/job_analysis.json"
  agent: job_analyst

candidate_profiling_task:
  description: >
    [[ dynamically generated in tasks.py to include structured input schema ]]
  expected_output: >
    A structured CandidateProfile containing relevant experiences, matching skills,
    key projects, achievements, and contextual information tailored to the job requirements.
  output_file: "{output_directory}/candidate_profile.json"
  context: [job_analysis_task]
  agent: candidate_profiler

cv_optimization_task:
  description: >
    [[ dynamically generated in tasks.py to include structured input schema ]]
  expected_output: >
    A CurriculumVitae object with restructured and rewritten content sections
    tailored specifically to the job requirements, optimized for both ATS
    and human review.
  output_file: "{output_directory}/cv_optimization.json"
  context: [job_analysis_task, candidate_profiling_task]
  agent: cv_strategist
