job_analysis_task:
  description: >
    Analyze the job posting URL provided ({job_posting_url}) and extract structured
    information into the JobPosting schema. Follow these rules:

    **1. Metadata**
    - Extract job title, company name, industry, full description, and experience level.

    **2. Requirements**
    - Extract degrees, certifications, and explicit "years of experience" requirements.
    - Identify hard requirements (licenses, mandatory credentials).

    **3. Skills**
    - Technical skills: programming languages, frameworks, cloud platforms, tools.
    - Soft skills: communication, teamwork, leadership, problem-solving.
    - Preferred skills: "nice-to-have" extras.

    **4. Responsibilities**
    - Bullet out day-to-day tasks, focusing on specific duties (not vague culture blurbs).

    **5. ATS Alignment**
    - Keywords: important phrases used in the posting for filtering.
    - Tools/tech stack: specific named technologies (AWS, Docker, React, etc).

    **6. Normalization**
    - Deduplicate terms (merge "Python 3" and "Python").
    - Expand acronyms if possible (e.g., "CI/CD" -> "Continuous Integration / Continuous Deployment").
    - Filter out vague corporate jargon ("fast-paced environment", "great culture").

    Output must be a valid JobPosting object.
  expected_output: >
    A validated JobPosting object with all fields populated where possible,
    ensuring consistency and ATS-awareness.
  output_file: "{output_directory}/job_analysis.json"
  agent: job_analyst

candidate_profiling_task:
  description: >
    You will receive structured job requirements from the job analysis task:

    [[JobPosting]]

    Your task is to build a comprehensive profile of the job candidate using the following approach:

    1. **Primary Data Source - CV Analysis:**
       Read the candidate's current CV at {candidate_cv_path} to extract basic information 
       like name, contact details, work history, and skills overview.

    2. **Knowledge Base Enhancement:**
       Use the CandidateKnowledgeBase tool to search for additional context and details 
       about the candidate's work experience and qualifications.

    When constructing the profile of the candidate, focus on:

    - Projects and experiences that match required and preferred skills
    - Relevant technical achievements and their business impact
    - Leadership and collaboration examples appropriate to the role level
    - Domain expertise aligned with the industry and responsibilities
    - Quantifiable results and measurable outcomes from past work

    Use semantic search to find related experiences, even if the match is not exact. 

    To use the SemanticSearchTool:
    - Always call it with exactly one argument: {"query": "<natural language text>"}
    - Do not pass structured data, JSON objects, or dictionaries as the query.
    - Convert the relevant job requirements into a single natural language query string first.
    - The tool returns relevant text chunks along with their source file paths.

    Example of correct usage:
    {"query": "Find projects and experiences related to backend engineering with Python and AWS in the fintech industry."}

    Example of incorrect usage (do NOT do this):
    {"query": {"description": "Python, AWS, backend"}}  

    When the SemanticSearchTool returns results, each result includes a "Source:" line 
    with the full file path. You can read the complete document using the FileReadTool with 
    that exact path to get additional context and details.

    Summarize and integrate retrieved findings into a structured CandidateProfile object
    tailored to the provided job requirements.
  expected_output: >
    A structured CandidateProfile containing relevant experiences, matching skills,
    key projects, achievements, and contextual information tailored to the job requirements.
  output_file: "{output_directory}/candidate_profile.json"
  context: [job_analysis_task]
  agent: candidate_profiler

cv_optimization_task:
  description: >
    You will receive three inputs to complete this task:

    1. A structured job posting object with the following fields:
    [[JobPosting]]

    2. A structured candidate profile object with the following fields:
    [[CandidateProfile]]

    3. A file path to the candidate's current CV:
    {candidate_cv_path}

    Use your file reading tool to read and analyze the candidate's current CV from this path. 
    The CV may be in various formats (JSON, YAML, CSV) and will need to be interpreted and 
    restructured into the output format.

    Your task is to optimize the candidate's CV for the target job by:
    - Prioritizing experiences that best match the required and preferred skills
    - Rewriting descriptions to emphasize relevant achievements and responsibilities
    - Optimizing keyword usage for applicant tracking system (ATS) compatibility
    - Structuring sections to highlight strengths for this specific role
    - Quantifying impact (e.g., metrics, results) wherever possible
    - Aligning language, tone, and terminology with the job posting

    Your final output must be a structured CurriculumVitae object that is tailored to the job requirements and enriched with the candidate’s strongest qualifications.
  expected_output: >
    A CurriculumVitae object with restructured and rewritten content sections
    tailored specifically to the job requirements, optimized for both ATS
    and human review.
  output_file: "{output_directory}/cv_optimization.json"
  context: [job_analysis_task, candidate_profiling_task]
  agent: cv_strategist
